# Generated by Django 4.2.7 on 2023-12-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
